import { ISkills } from '../../types/skill';

export const skills: ISkills[] = [
  {
    category: 'Technologies',
    items: [
      'Typescript',
      'JavaScript',
      'Node.js',
      'Sass (SCSS)',
      'Styled Components',
      'CSS Modules',
      'Tailwind',
      'Material UI',
      'Ant Design',
      'Chakra UI',
      'CSS',
      'HTML',
      'Async',
      'Web Sockets',
      'Yup',
      'GraphQL',
      'Formik',
    ],
  },
  {
    category: 'Frameworks',
    items: [
      'React',
      'Next.js',
      'Gatsby',
      'Redux/Redux Toolkit',
      'MobX',
      'Express',
      'NestJS',
    ],
  },
  {
    category: 'Task and Project Management',
    items: ['Git', 'Trello', 'Jira'],
  },
  {
    category: 'Tools',
    items: [
      'NPM',
      'Webpack',
      'ESLint',
      'Figma',
      'Photoshop',
      'Visual Studio Code',
    ],
  },
  {
    category: 'Methodologies',
    items: ['BEM', 'OOCSS', 'SMACSS', 'ECSS'],
  },
  {
    category: 'Programming Paradigms',
    items: [
      'OOP',
      'Functional programming',
      'Data Structure',
      'Design Patterns',
      'Algorithms',
      'Basics of Java, C#, C++, Python, Go',
    ],
  },
  {
    category: 'Architecture',
    items: [
      'MVC',
      'SOLID',
      'REST',
      'API',
      'Microservices',
      'Clean Architecture',
      'DDD',
    ],
  },
  {
    category: 'Databases',
    items: [
      'Database design',
      'SQL',
      'SQLite',
      'PostgreSQL',
      'MongoDB',
      'Mongoose',
      'TypeORM',
      'Sequelize',
      'Migrations',
      'Seeds',
      'Transactions',
    ],
  },
  {
    category: 'DevOps',
    items: [
      'Docker',
      'Kubernetes',
      'AWS',
      'Google Cloud',
      'Heroku',
      'Firebase',
      'Cloudflare',
      'CI/CD',
    ],
  },
  {
    category: 'English',
    items: ['Advanced (C1+)'],
  },
  {
    category: 'Others',
    items: ['UI/UX Design'],
  },
];
